/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedRachaoRouteImport } from './routes/_authenticated/rachao'
import { Route as AuthenticatedSorteioRouteImport } from './routes/_authenticated/sorteio'
import { Route as AuthenticatedTimeRouteImport } from './routes/_authenticated/time'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRachaoRoute = AuthenticatedRachaoRouteImport.update({
  id: '/rachao',
  path: '/rachao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSorteioRoute = AuthenticatedSorteioRouteImport.update({
  id: '/sorteio',
  path: '/sorteio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimeRoute = AuthenticatedTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/rachao': typeof AuthenticatedRachaoRoute
  '/sorteio': typeof AuthenticatedSorteioRoute
  '/time': typeof AuthenticatedTimeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/rachao': typeof AuthenticatedRachaoRoute
  '/sorteio': typeof AuthenticatedSorteioRoute
  '/time': typeof AuthenticatedTimeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/rachao': typeof AuthenticatedRachaoRoute
  '/_authenticated/sorteio': typeof AuthenticatedSorteioRoute
  '/_authenticated/time': typeof AuthenticatedTimeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/admin' | '/rachao' | '/sorteio' | '/time'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/admin' | '/rachao' | '/sorteio' | '/time'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/rachao'
    | '/_authenticated/sorteio'
    | '/_authenticated/time'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rachao': {
      id: '/_authenticated/rachao'
      path: '/rachao'
      fullPath: '/rachao'
      preLoaderRoute: typeof AuthenticatedRachaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sorteio': {
      id: '/_authenticated/sorteio'
      path: '/sorteio'
      fullPath: '/sorteio'
      preLoaderRoute: typeof AuthenticatedSorteioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/time': {
      id: '/_authenticated/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof AuthenticatedTimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedRachaoRoute: typeof AuthenticatedRachaoRoute
  AuthenticatedSorteioRoute: typeof AuthenticatedSorteioRoute
  AuthenticatedTimeRoute: typeof AuthenticatedTimeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedRachaoRoute: AuthenticatedRachaoRoute,
  AuthenticatedSorteioRoute: AuthenticatedSorteioRoute,
  AuthenticatedTimeRoute: AuthenticatedTimeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
