/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RachaoRouteImport } from './routes/rachao'
import { Route as SorteioRouteImport } from './routes/sorteio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RachaoRoute = RachaoRouteImport.update({
  id: '/rachao',
  path: '/rachao',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteioRoute = SorteioRouteImport.update({
  id: '/sorteio',
  path: '/sorteio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rachao': typeof RachaoRoute
  '/sorteio': typeof SorteioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rachao': typeof RachaoRoute
  '/sorteio': typeof SorteioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rachao': typeof RachaoRoute
  '/sorteio': typeof SorteioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rachao' | '/sorteio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rachao' | '/sorteio'
  id: '__root__' | '/' | '/rachao' | '/sorteio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RachaoRoute: typeof RachaoRoute
  SorteioRoute: typeof SorteioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rachao': {
      id: '/rachao'
      path: '/rachao'
      fullPath: '/rachao'
      preLoaderRoute: typeof RachaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteio': {
      id: '/sorteio'
      path: '/sorteio'
      fullPath: '/sorteio'
      preLoaderRoute: typeof SorteioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RachaoRoute: RachaoRoute,
  SorteioRoute: SorteioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
