/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRachaoRouteImport } from './routes/_authenticated/rachao'
import { Route as AuthenticatedSorteioRouteImport } from './routes/_authenticated/sorteio'
import { Route as AuthenticatedTimeRouteImport } from './routes/_authenticated/time'

const AuthenticatedRachaoRoute = AuthenticatedRachaoRouteImport.update({
  id: '/_authenticated/rachao',
  path: '/rachao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSorteioRoute = AuthenticatedSorteioRouteImport.update({
  id: '/_authenticated/sorteio',
  path: '/sorteio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimeRoute = AuthenticatedTimeRouteImport.update({
  id: '/_authenticated/time',
  path: '/time',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/rachao': typeof AuthenticatedRachaoRoute
  '/sorteio': typeof AuthenticatedSorteioRoute
  '/time': typeof AuthenticatedTimeRoute
}
export interface FileRoutesByTo {
  '/rachao': typeof AuthenticatedRachaoRoute
  '/sorteio': typeof AuthenticatedSorteioRoute
  '/time': typeof AuthenticatedTimeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/rachao': typeof AuthenticatedRachaoRoute
  '/_authenticated/sorteio': typeof AuthenticatedSorteioRoute
  '/_authenticated/time': typeof AuthenticatedTimeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/rachao' | '/sorteio' | '/time'
  fileRoutesByTo: FileRoutesByTo
  to: '/rachao' | '/sorteio' | '/time'
  id:
    | '__root__'
    | '/_authenticated/rachao'
    | '/_authenticated/sorteio'
    | '/_authenticated/time'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRachaoRoute: typeof AuthenticatedRachaoRoute
  AuthenticatedSorteioRoute: typeof AuthenticatedSorteioRoute
  AuthenticatedTimeRoute: typeof AuthenticatedTimeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/rachao': {
      id: '/_authenticated/rachao'
      path: '/rachao'
      fullPath: '/rachao'
      preLoaderRoute: typeof AuthenticatedRachaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sorteio': {
      id: '/_authenticated/sorteio'
      path: '/sorteio'
      fullPath: '/sorteio'
      preLoaderRoute: typeof AuthenticatedSorteioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/time': {
      id: '/_authenticated/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof AuthenticatedTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRachaoRoute: AuthenticatedRachaoRoute,
  AuthenticatedSorteioRoute: AuthenticatedSorteioRoute,
  AuthenticatedTimeRoute: AuthenticatedTimeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
